//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PacemakerStatus) DeepCopyInto(out *PacemakerStatus) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PacemakerStatus.
func (in *PacemakerStatus) DeepCopy() *PacemakerStatus {
	if in == nil {
		return nil
	}
	out := new(PacemakerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PacemakerStatus) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PacemakerStatusList) DeepCopyInto(out *PacemakerStatusList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PacemakerStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PacemakerStatusList.
func (in *PacemakerStatusList) DeepCopy() *PacemakerStatusList {
	if in == nil {
		return nil
	}
	out := new(PacemakerStatusList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PacemakerStatusList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PacemakerStatusSpec) DeepCopyInto(out *PacemakerStatusSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PacemakerStatusSpec.
func (in *PacemakerStatusSpec) DeepCopy() *PacemakerStatusSpec {
	if in == nil {
		return nil
	}
	out := new(PacemakerStatusSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PacemakerStatusStatus) DeepCopyInto(out *PacemakerStatusStatus) {
	*out = *in
	in.LastUpdated.DeepCopyInto(&out.LastUpdated)
	out.Summary = in.Summary
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PacemakerStatusStatus.
func (in *PacemakerStatusStatus) DeepCopy() *PacemakerStatusStatus {
	if in == nil {
		return nil
	}
	out := new(PacemakerStatusStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PacemakerSummary) DeepCopyInto(out *PacemakerSummary) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PacemakerSummary.
func (in *PacemakerSummary) DeepCopy() *PacemakerSummary {
	if in == nil {
		return nil
	}
	out := new(PacemakerSummary)
	in.DeepCopyInto(out)
	return out
}
