FROM registry.ci.openshift.org/ocp/builder:rhel-9-golang-1.23-openshift-4.19 AS builder
WORKDIR /go/src/github.com/openshift/cluster-etcd-operator
COPY . .
ENV GO_PACKAGE github.com/openshift/cluster-etcd-operator
RUN make build --warn-undefined-variables

FROM registry.ci.openshift.org/ocp/4.18:base-rhel9
COPY --from=builder /go/src/github.com/openshift/cluster-etcd-operator/tnf-operator /usr/bin/

LABEL io.openshift.release.operator true
