FROM registry.svc.ci.openshift.org/ocp/builder:golang-1.13 AS builder
WORKDIR /go/src/github.com/openshift/cluster-etcd-operator
COPY . .
RUN make build --warn-undefined-variables

FROM registry.svc.ci.openshift.org/ocp/4.4:base
COPY bindata/bootkube/* /usr/share/bootkube/manifests/
COPY bindata/bootkube/config/* /usr/share/bootkube/manifests/config/
COPY bindata/bootkube/manifests/* /usr/share/bootkube/manifests/manifests/
COPY bindata/bootkube/bootstrap-manifests/* /usr/share/bootkube/manifests/bootstrap-manifests/
COPY manifests/ /manifests/
COPY --from=builder /go/src/github.com/openshift/cluster-etcd-operator/cluster-etcd-operator /usr/bin/

LABEL io.openshift.release.operator true
