apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: system:openshift:etcd-operator-cluster-role
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - secrets
      - namespaces
      - nodes
      # only openshift-etcd
      - pods
      - services
      - endpoints
      - serviceaccounts
    # TODO(thomas): this is very broad, we need to be concise here across all namespaces (especially with secrets)
    verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]
  - apiGroups:
      - config.openshift.io
    resources:
      - apiservers
      - clusterversions
      - infrastructures
      - networks
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - config.openshift.io
    resourceNames:
      - etcd
    resources:
      - clusteroperators
      - clusteroperators/status
    verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]
  - apiGroups:
      - operator.openshift.io
    resources:
      - etcds
    verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]
  - apiGroups:
      - operator.openshift.io
    resourceNames:
      - cluster
    resources:
      - etcds/status
    verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - clusterrolebindings
      - clusterrole
      - role
      - rolebinding
    verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]
  - apiGroups:
      - machine.openshift.io
    resources:
      - machinehealthchecks
      - machines
      - machinesets
    verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]
  - apiGroups:
      - policy
    resources:
      - poddisruptionbudgets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]
