apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: etcd-operator-cluster-role
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
  rules:
  - apiGroups:
    - ""
    resources:
    - configmaps
    verbs:
    - get
    - list
    - patch
    - update
    - watch
  - apiGroups:
    - ""
    resources:
    - namespaces
    - nodes
    - secrets
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - ""
    resources:
    - pods
    verbs:
    - get
  - apiGroups:
    - config.openshift.io
    resources:
    - apiservers
    - clusteroperators
    - clusterversions
    - infrastructures
    - networks
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - config.openshift.io
    resourceNames:
    - etcd
    resources:
    - clusteroperators/status
    verbs:
    - get
    - patch
    - update
  - apiGroups:
    - operator.openshift.io
    resources:
    - etcds
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - operator.openshift.io
    resourceNames:
    - cluster
    resources:
    - etcds/status
    verbs:
    - get
    - patch
    - update
  - apiGroups:
    - rbac.authorization.k8s.io
    resources:
    - clusterrolebindings
    verbs:
    - get
    - list
    - watch