apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: openshift-etcd-operator
  name: etcd-operator
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
