apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  namespace: openshift-etcd
  name: etcd-quorum-guard
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    exclude.release.openshift.io/internal-openshift-hosted: "true"
    include.release.openshift.io/single-node-production-edge: "true"
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      k8s-app: etcd-quorum-guard
