---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: openshift-machine-config-operator
  name: pdb-mco
rules:
- apiGroups: ["policy"]
  resources: ["poddisruptionbudgets"]
  verbs: ["get", "watch", "list", "delete", "create", "update"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["*"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: pdb-mco
  namespace: openshift-etcd-operator
subjects:
- kind: ServiceAccount
  name: default
  namespace: openshift-etcd-operator
roleRef:
  kind: Role
  namespace: openshift-etcd-operator
  name: pdb-mco
  apiVersion: rbac.authorization.k8s.io/v1beta1

