apiVersion: operator.openshift.io/v1
kind: Etcd
metadata:
  name: cluster
  annotations:
    release.openshift.io/create-only: "true"
spec:
  managementState: Managed
  # TODO this clearly needs to be fixed
  imagePullSpec: openshift/origin-hypershift:latest
