apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: etcd-operator-role
  namespace: openshift-etcd-operator
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
  rules:
  - apiGroups:
    - ""
    resourceNames:
    - openshift-cluster-etcd-operator-lock
    resources:
    - configmaps
    verbs:
    - get
    - patch
    - update
  - apiGroups:
    - coordination.k8s.io
    resourceNames:
    - openshift-cluster-etcd-operator-lock
    resources:
    - leases
    verbs:
    - get
    - patch
    - update
  - apiGroups:
    - ""
    resources:
    - configmaps
    verbs:
    - create
  - apiGroups:
    - ""
    resources:
    - endpoints
    - pods
    - serviceaccounts
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - ""
    resources:
    - pods
    verbs:
    - create
    - get
    - list
    - watch
  - apiGroups:
    - ""
    resourceNames:
    - etcd-all-certs-6
    resources:
    - secrets
    verbs:
    - create
  - apiGroups:
    - ""
    resourceNames:
    - etcd
    resources:
    - services
    verbs:
    - get
  - apiGroups:
    - apps
    resourceNames:
    - etcd-quorum-guard
    resources:
    - deployments
    verbs:
    - get
    - patch
    - update
  - apiGroups:
    - policy
    resourceNames:
    - etcd-quorum-guard
    resources:
    - poddisruptionbudgets
    verbs:
    - get
  - apiGroups:
    - ""
    resourceNames:
    - revision-status-1
    resources:
    - configmaps
    verbs:
    - delete