apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: system:openshift:operator:etcd-operator
  namespace: openshift-etcd-operator
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
roleRef:
  kind: Role
  name: etcd-operator-role
subjects:
- kind: ServiceAccount
  namespace: openshift-etcd-operator
  name: etcd-operator
