// Code generated by go-bindata.
// sources:
// bindata/v4.3.0/etcd/cm.yaml
// bindata/v4.3.0/etcd/defaultconfig.yaml
// bindata/v4.3.0/etcd/ns.yaml
// bindata/v4.3.0/etcd/operator-config.yaml
// bindata/v4.3.0/etcd/pod-cm.yaml
// bindata/v4.3.0/etcd/pod.yaml
// bindata/v4.3.0/etcd/sa.yaml
// bindata/v4.3.0/etcd/svc.yaml
// DO NOT EDIT!

package v430_00_assets

import (
	"fmt"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
	"time"
)

type asset struct {
	bytes []byte
	info  os.FileInfo
}

type bindataFileInfo struct {
	name    string
	size    int64
	mode    os.FileMode
	modTime time.Time
}

func (fi bindataFileInfo) Name() string {
	return fi.name
}
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}
func (fi bindataFileInfo) IsDir() bool {
	return false
}
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var _v430EtcdCmYaml = []byte(`apiVersion: v1
kind: ConfigMap
metadata:
  namespace: openshift-etcd
  name: config
data:
  config.yaml:
`)

func v430EtcdCmYamlBytes() ([]byte, error) {
	return _v430EtcdCmYaml, nil
}

func v430EtcdCmYaml() (*asset, error) {
	bytes, err := v430EtcdCmYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "v4.3.0/etcd/cm.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _v430EtcdDefaultconfigYaml = []byte(`apiVersion: kubecontrolplane.config.openshift.io/v1
kind: EtcdConfig
`)

func v430EtcdDefaultconfigYamlBytes() ([]byte, error) {
	return _v430EtcdDefaultconfigYaml, nil
}

func v430EtcdDefaultconfigYaml() (*asset, error) {
	bytes, err := v430EtcdDefaultconfigYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "v4.3.0/etcd/defaultconfig.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _v430EtcdNsYaml = []byte(`apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/node-selector: ""
  name: openshift-etcd
  labels:
    openshift.io/run-level: "0"
`)

func v430EtcdNsYamlBytes() ([]byte, error) {
	return _v430EtcdNsYaml, nil
}

func v430EtcdNsYaml() (*asset, error) {
	bytes, err := v430EtcdNsYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "v4.3.0/etcd/ns.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _v430EtcdOperatorConfigYaml = []byte(`apiVersion: operator.openshift.io/v1
kind: Etcd
metadata:
  name: cluster
spec:
  managementState: Managed
  # TODO this clearly needs to be fixed
  imagePullSpec: openshift/origin-hypershift:latest
`)

func v430EtcdOperatorConfigYamlBytes() ([]byte, error) {
	return _v430EtcdOperatorConfigYaml, nil
}

func v430EtcdOperatorConfigYaml() (*asset, error) {
	bytes, err := v430EtcdOperatorConfigYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "v4.3.0/etcd/operator-config.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _v430EtcdPodCmYaml = []byte(`apiVersion: v1
kind: ConfigMap
metadata:
  namespace: openshift-etcd
  name: etcd-pod
data:
  pod.yaml:
  forceRedeploymentReason:
  version:
`)

func v430EtcdPodCmYamlBytes() ([]byte, error) {
	return _v430EtcdPodCmYaml, nil
}

func v430EtcdPodCmYaml() (*asset, error) {
	bytes, err := v430EtcdPodCmYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "v4.3.0/etcd/pod-cm.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _v430EtcdPodYaml = []byte(`apiVersion: v1
kind: Pod
metadata:
  name: openshift-etcd
  namespace: openshift-etcd
  labels:
    app: etcd
    etcd: "true"
    revision: "REVISION"
spec:
  containers:
  - name: openshift-etcd
    image: ${IMAGE}
    imagePullPolicy: Always
    terminationMessagePolicy: FallbackToLogsOnError
    command: ["sleep"]
    args:
    - "7200"
    resources:
      requests:
        memory: 200Mi
        cpu: 100m
    ports:
      - containerPort: 10257
    volumeMounts:
    - mountPath: /etc/kubernetes/static-pod-resources
      name: resource-dir
#    livenessProbe:
#      httpGet:
#        scheme: HTTPS
#        port: 10257
#        path: healthz
#      initialDelaySeconds: 45
#      timeoutSeconds: 10
#    readinessProbe:
#      httpGet:
#        scheme: HTTPS
#        port: 10257
#        path: healthz
#      initialDelaySeconds: 10
#      timeoutSeconds: 10
  hostNetwork: true
  priorityClassName: system-node-critical
  tolerations:
  - operator: "Exists"
  volumes:
  - hostPath:
      path: /etc/kubernetes/static-pod-resources/etcd-pod-REVISION
    name: resource-dir

`)

func v430EtcdPodYamlBytes() ([]byte, error) {
	return _v430EtcdPodYaml, nil
}

func v430EtcdPodYaml() (*asset, error) {
	bytes, err := v430EtcdPodYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "v4.3.0/etcd/pod.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _v430EtcdSaYaml = []byte(`apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: openshift-etcd
  name: etcd-sa
`)

func v430EtcdSaYamlBytes() ([]byte, error) {
	return _v430EtcdSaYaml, nil
}

func v430EtcdSaYaml() (*asset, error) {
	bytes, err := v430EtcdSaYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "v4.3.0/etcd/sa.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _v430EtcdSvcYaml = []byte(`apiVersion: v1
kind: Service
metadata:
  namespace: openshift-etcd
  name: etcd
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: serving-cert
    prometheus.io/scrape: "true"
    prometheus.io/scheme: https
spec:
  selector:
    etcd: "true"
  ports:
  - name: https
    port: 443
    targetPort: 10257
`)

func v430EtcdSvcYamlBytes() ([]byte, error) {
	return _v430EtcdSvcYaml, nil
}

func v430EtcdSvcYaml() (*asset, error) {
	bytes, err := v430EtcdSvcYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "v4.3.0/etcd/svc.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"v4.3.0/etcd/cm.yaml":              v430EtcdCmYaml,
	"v4.3.0/etcd/defaultconfig.yaml":   v430EtcdDefaultconfigYaml,
	"v4.3.0/etcd/ns.yaml":              v430EtcdNsYaml,
	"v4.3.0/etcd/operator-config.yaml": v430EtcdOperatorConfigYaml,
	"v4.3.0/etcd/pod-cm.yaml":          v430EtcdPodCmYaml,
	"v4.3.0/etcd/pod.yaml":             v430EtcdPodYaml,
	"v4.3.0/etcd/sa.yaml":              v430EtcdSaYaml,
	"v4.3.0/etcd/svc.yaml":             v430EtcdSvcYaml,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}

var _bintree = &bintree{nil, map[string]*bintree{
	"v4.3.0": {nil, map[string]*bintree{
		"openshift-etcd": {nil, map[string]*bintree{
			"cm.yaml":              {v430EtcdCmYaml, map[string]*bintree{}},
			"defaultconfig.yaml":   {v430EtcdDefaultconfigYaml, map[string]*bintree{}},
			"ns.yaml":              {v430EtcdNsYaml, map[string]*bintree{}},
			"operator-config.yaml": {v430EtcdOperatorConfigYaml, map[string]*bintree{}},
			"pod-cm.yaml":          {v430EtcdPodCmYaml, map[string]*bintree{}},
			"pod.yaml":             {v430EtcdPodYaml, map[string]*bintree{}},
			"sa.yaml":              {v430EtcdSaYaml, map[string]*bintree{}},
			"svc.yaml":             {v430EtcdSvcYaml, map[string]*bintree{}},
		}},
	}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}
