apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: tnf-cert-watcher
  namespace: openshift-etcd
  labels:
    app.kubernetes.io/name: tnf-cert-watcher
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: tnf-cert-watcher
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tnf-cert-watcher
      annotations:
        openshift.io/required-scc: "privileged"
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: cert-watcher
          image: <injected>
          imagePullPolicy: IfNotPresent
          command: ["tnf-monitor", "watch-certs", "--cert-dir=/certs/configmaps/etcd-all-bundles"]
          terminationMessagePolicy: FallbackToLogsOnError
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
          securityContext:
            privileged: true
            allowPrivilegeEscalation: true
          volumeMounts:
            - name: etcd-certs
              mountPath: /certs
              readOnly: true
      hostIPC: false
      hostNetwork: false
      hostPID: true
      serviceAccountName: tnf-setup-manager
      priorityClassName: system-node-critical
      nodeSelector:
        node-role.kubernetes.io/master: ""
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
        - key: node.kubernetes.io/memory-pressure
          operator: Exists
          effect: NoSchedule
        - key: node.kubernetes.io/disk-pressure
          operator: Exists
          effect: NoSchedule
        - key: node.kubernetes.io/pid-pressure
          operator: Exists
          effect: NoSchedule
      volumes:
        - name: etcd-certs
          hostPath:
            path: /etc/kubernetes/static-pod-resources/etcd-certs
            type: Directory
