apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: tnf-setup
  name: tnf-setup-clusterrole
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - operator.openshift.io
    resources:
      - etcds
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - operator.openshift.io
    resources:
      - etcds/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - etcd.openshift.io
    resources:
      - pacemakerclusters
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
  - apiGroups:
      - etcd.openshift.io
    resources:
      - pacemakerclusters/status
    verbs:
      - get
      - update
      - patch
  - apiGroups:
      - config.openshift.io
    resources:
      - clusterversions
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - security.openshift.io
    resourceNames:
      - privileged
    resources:
      - securitycontextconstraints
    verbs:
      - use
