apiVersion: batch/v1
kind: CronJob
metadata:
  name: <injected>
  namespace: <injected>
  labels:
    app.kubernetes.io/name: <injected>
spec:
  schedule: <injected>
  concurrencyPolicy: "Forbid"
  startingDeadlineSeconds: 120
  failedJobsHistoryLimit: 3
  successfulJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      labels:
        app.kubernetes.io/name: <injected>
    spec:
      activeDeadlineSeconds: 90
      ttlSecondsAfterFinished: 600
      template:
        metadata:
          annotations:
            openshift.io/required-scc: "privileged"
          labels:
            app.kubernetes.io/name: <injected>
        spec:
          terminationGracePeriodSeconds: 5
          containers:
            - name: collector
              image: <injected>
              imagePullPolicy: IfNotPresent
              terminationMessagePolicy: FallbackToLogsOnError
              command: ["<injected>"]
              resources:
                requests:
                  cpu: 10m
                  memory: 32Mi
              securityContext:
                privileged: true
                allowPrivilegeEscalation: true
          hostIPC: false
          hostNetwork: false
          hostPID: true
          serviceAccountName: tnf-setup-manager
          nodeSelector:
            node-role.kubernetes.io/master: ""
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: node.kubernetes.io/not-ready
                    operator: DoesNotExist
                  - key: node.kubernetes.io/unreachable
                    operator: DoesNotExist
          tolerations:
            - key: node-role.kubernetes.io/master
              operator: Exists
              effect: NoSchedule
            - key: node.kubernetes.io/memory-pressure
              operator: Exists
              effect: NoSchedule
            - key: node.kubernetes.io/disk-pressure
              operator: Exists
              effect: NoSchedule
            - key: node.kubernetes.io/pid-pressure
              operator: Exists
              effect: NoSchedule
          restartPolicy: Never
