apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app.kubernetes.io/name: <injected>
  namespace: openshift-etcd
  name: <injected>
spec:
  template:
    metadata:
      annotations:
        openshift.io/required-scc: "privileged"
    spec:
      containers:
        - name: tnf-job
          image: <injected>
          imagePullPolicy: IfNotPresent
          command: [ "tnf-runtime", "<injected>" ]
          terminationMessagePolicy: FallbackToLogsOnError
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
          securityContext:
            privileged: true
            allowPrivilegeEscalation: true
      hostIPC: false
      hostNetwork: false
      hostPID: true
      priorityClassName: system-node-critical
      serviceAccountName: tnf-setup-manager
      terminationGracePeriodSeconds: 10
      restartPolicy: Never
  backoffLimit: 3
