apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: tnf-setup
  namespace: openshift-etcd
  name: tnf-setup-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tnf-setup-role
subjects:
  - kind: ServiceAccount
    name: tnf-setup-manager
    namespace: openshift-etcd
