apiVersion: batch/v1
kind: Job
metadata:
  name: cluster-backup-job
  namespace: openshift-etcd
  labels:
    app: cluster-backup-job
    backup-name: templated
spec:
  template:
    spec:
      initContainers:
        - name: verify-storage
          imagePullPolicy: IfNotPresent
          terminationMessagePolicy: FallbackToLogsOnError
          command: [ "cluster-etcd-operator", "verify", "backup-storage" ]
          securityContext:
            privileged: true
          resources:
            requests:
              memory: 50Mi
              cpu: 5m
          volumeMounts:
            - mountPath: /var/lib/etcd-auto-backup
              name: etcd-auto-backup-dir
            - mountPath: /var/run/secrets/etcd-client
              name: etcd-client
            - mountPath: /var/run/configmaps/etcd-ca
              name: etcd-ca
      containers:
        - name: cluster-backup
          imagePullPolicy: IfNotPresent
          terminationMessagePolicy: FallbackToLogsOnError
          command:
            - /bin/sh
            - -c
            - |
              #!/bin/sh
              set -exuo pipefail

              cluster-etcd-operator cluster-backup --backup-dir "${CLUSTER_BACKUP_PATH}"

          resources:
            requests:
              memory: 80Mi
              cpu: 10m
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /usr/local/bin
              name: usr-local-bin
            - mountPath: /etc/kubernetes/static-pod-resources
              name: resources-dir
            - mountPath: /etc/kubernetes/static-pod-certs
              name: cert-dir
            - mountPath: /etc/kubernetes/manifests
              name: static-pod-dir
            - mountPath: /var/lib/etcd-auto-backup
              name: etcd-auto-backup-dir
            - mountPath: /var/run/secrets/etcd-client
              name: etcd-client
            - mountPath: /var/run/configmaps/etcd-ca
              name: etcd-ca
      priorityClassName: system-node-critical
      activeDeadlineSeconds: 900
      nodeSelector:
        node-role.kubernetes.io/master: ""
      restartPolicy: Never
      hostNetwork: true
      tolerations:
        - operator: "Exists"
      volumes:
        - hostPath:
            path: /usr/local/bin
          name: usr-local-bin
        - hostPath:
            path: /etc/kubernetes/manifests
          name: static-pod-dir
        - hostPath:
            path: /etc/kubernetes/static-pod-resources
          name: resources-dir
        - hostPath:
            path: /etc/kubernetes/static-pod-resources/etcd-certs
          name: cert-dir
        - name: etcd-client
          secret:
            secretName: etcd-client
        - name: etcd-ca
          configMap:
            name: etcd-ca-bundle
        - name: etcd-auto-backup-dir
          hostPath:
            path: /var/lib/etcd-auto-backup
