apiVersion: batch/v1
kind: CronJob
metadata:
  name: templated
  namespace: openshift-etcd
  labels:
    app: cluster-backup-cronjob
    backup-name: templated
spec:
  schedule: "templated"
  concurrencyPolicy: "Forbid"
  failedJobsHistoryLimit: 10
  successfulJobsHistoryLimit: 5
  jobTemplate:
    metadata:
      labels:
        app: cluster-backup-cronjob
    spec:
      template:
        metadata:
          labels:
            app: cluster-backup-cronjob
        spec:
          initContainers:
            - name: retention
              imagePullPolicy: IfNotPresent
              terminationMessagePolicy: FallbackToLogsOnError
              # since we can expect hostPath mounts, we need to run as privileged to access them
              securityContext:
                privileged: true
              command: [ "cluster-etcd-operator" ]
              args: [ "templated" ]
              volumeMounts:
                - mountPath: /var/lib/etcd-auto-backup
                  name: etcd-auto-backup-dir
          containers:
            - name: cluster-backup
              imagePullPolicy: IfNotPresent
              terminationMessagePolicy: FallbackToLogsOnError
              command: [ "cluster-etcd-operator" ]
              args: [ "templated" ]
              env:
                - name: MY_JOB_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.labels['batch.kubernetes.io/job-name']
                - name: MY_JOB_UID
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.labels['batch.kubernetes.io/controller-uid']
          serviceAccountName: etcd-backup-sa
          nodeSelector:
            node-role.kubernetes.io/master: ""
          tolerations:
            - operator: "Exists"
          restartPolicy: OnFailure
          volumes:
            - name: etcd-auto-backup-dir
              hostPath:
                path: /var/lib/etcd-auto-backup

