apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: etcd-sa-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: etcd-sa-clusterrole
subjects:
  - kind: ServiceAccount
    name: etcd-sa
    namespace: openshift-etcd
