apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: etcd-quorum-guard
  namespace: openshift-etcd
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      k8s-app: etcd-quorum-guard

